import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import WrapLayout from './components/WrapLayout'

const roboto = Roboto({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Saigon Xanh',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <WrapLayout>{children}</WrapLayout>
      </body>
    </html>
  )
}
